set(_CATKIN_CURRENT_PACKAGE "numpy_helper_functions")
set(numpy_helper_functions_VERSION "1.0.0")
set(numpy_helper_functions_MAINTAINER "Hector Herrero <hector.herrero@tecnalia.com>")
set(numpy_helper_functions_PACKAGE_FORMAT "2")
set(numpy_helper_functions_BUILD_DEPENDS )
set(numpy_helper_functions_BUILD_EXPORT_DEPENDS )
set(numpy_helper_functions_BUILDTOOL_DEPENDS "catkin")
set(numpy_helper_functions_BUILDTOOL_EXPORT_DEPENDS )
set(numpy_helper_functions_EXEC_DEPENDS "tf" "python-numpy")
set(numpy_helper_functions_RUN_DEPENDS "tf" "python-numpy")
set(numpy_helper_functions_TEST_DEPENDS )
set(numpy_helper_functions_DOC_DEPENDS )
set(numpy_helper_functions_URL_WEBSITE "")
set(numpy_helper_functions_URL_BUGTRACKER "")
set(numpy_helper_functions_URL_REPOSITORY "")
set(numpy_helper_functions_DEPRECATED "")