set(_CATKIN_CURRENT_PACKAGE "geometry_msgs_helper_functions")
set(geometry_msgs_helper_functions_VERSION "1.0.0")
set(geometry_msgs_helper_functions_MAINTAINER "Hector Herrero <hector.herrero@tecnalia.com>")
set(geometry_msgs_helper_functions_PACKAGE_FORMAT "2")
set(geometry_msgs_helper_functions_BUILD_DEPENDS "geometry_msgs" "tf")
set(geometry_msgs_helper_functions_BUILD_EXPORT_DEPENDS "geometry_msgs" "tf")
set(geometry_msgs_helper_functions_BUILDTOOL_DEPENDS "catkin")
set(geometry_msgs_helper_functions_BUILDTOOL_EXPORT_DEPENDS )
set(geometry_msgs_helper_functions_EXEC_DEPENDS "numpy_helper_functions" "geometry_msgs" "tf")
set(geometry_msgs_helper_functions_RUN_DEPENDS "numpy_helper_functions" "geometry_msgs" "tf")
set(geometry_msgs_helper_functions_TEST_DEPENDS "rospy" "rostest")
set(geometry_msgs_helper_functions_DOC_DEPENDS )
set(geometry_msgs_helper_functions_URL_WEBSITE "")
set(geometry_msgs_helper_functions_URL_BUGTRACKER "")
set(geometry_msgs_helper_functions_URL_REPOSITORY "")
set(geometry_msgs_helper_functions_DEPRECATED "")