set(_CATKIN_CURRENT_PACKAGE "eigen_helper_functions")
set(eigen_helper_functions_VERSION "1.0.0")
set(eigen_helper_functions_MAINTAINER "aitor.ibarguren <aitor.ibarguren@todo.todo>")
set(eigen_helper_functions_PACKAGE_FORMAT "1")
set(eigen_helper_functions_BUILD_DEPENDS "cmake_modules" "eigen")
set(eigen_helper_functions_BUILD_EXPORT_DEPENDS )
set(eigen_helper_functions_BUILDTOOL_DEPENDS "catkin")
set(eigen_helper_functions_BUILDTOOL_EXPORT_DEPENDS )
set(eigen_helper_functions_EXEC_DEPENDS )
set(eigen_helper_functions_RUN_DEPENDS )
set(eigen_helper_functions_TEST_DEPENDS "rosunit")
set(eigen_helper_functions_DOC_DEPENDS )
set(eigen_helper_functions_URL_WEBSITE "")
set(eigen_helper_functions_URL_BUGTRACKER "")
set(eigen_helper_functions_URL_REPOSITORY "")
set(eigen_helper_functions_DEPRECATED "")