set(_CATKIN_CURRENT_PACKAGE "tf_helper_functions")
set(tf_helper_functions_VERSION "1.0.0")
set(tf_helper_functions_MAINTAINER "Hector Herrero <hector.herrero@tecnalia.com>")
set(tf_helper_functions_PACKAGE_FORMAT "2")
set(tf_helper_functions_BUILD_DEPENDS "message_generation" "geometry_msgs")
set(tf_helper_functions_BUILD_EXPORT_DEPENDS "message_runtime")
set(tf_helper_functions_BUILDTOOL_DEPENDS "catkin")
set(tf_helper_functions_BUILDTOOL_EXPORT_DEPENDS )
set(tf_helper_functions_EXEC_DEPENDS "message_runtime" "tf2_ros" "geometry_msgs")
set(tf_helper_functions_RUN_DEPENDS "message_runtime" "tf2_ros" "geometry_msgs")
set(tf_helper_functions_TEST_DEPENDS )
set(tf_helper_functions_DOC_DEPENDS )
set(tf_helper_functions_URL_WEBSITE "")
set(tf_helper_functions_URL_BUGTRACKER "")
set(tf_helper_functions_URL_REPOSITORY "")
set(tf_helper_functions_DEPRECATED "")